services:
  orders-api:
    image: docker-lab/orders-api:latest
    container_name: backend-orders-api
    build:
      context: ./backend
    ports:
      - "8081:8080"
    environment:
      SOME_ENV_VAR: "some value"
      DEBUG: true
    env_file: ".env"
